/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface StrategicPillar {
  title: string;
  explanation: string;
}

export interface ProductStrategy {
  vision: string;
  mission: string;
  uniqueValueProp: string;
  strategicPillars: StrategicPillar[];
  positioningMatrix: {
    axisX: string;
    axisY: string;
    notes: string;
  };
}

export interface TeamRole {
  id: string; // UUID
  title: string;
  count: number;
  responsibilities: string[];
  tools: string[];
  vibe: string;
}

export interface TeamStructure {
  teamName: string;
  roles: TeamRole[];
  workflowRule: string;
  synergyNotes: string;
}

export interface WorkflowPhase {
  id: string; // UUID
  phaseName: string;
  description: string;
  input: string;
  process: string;
  output: string;
  timelineEstimate: string;
}

export interface Deliverable {
  id: string; // UUID
  name: string;
  category: 'code' | 'design' | 'strategy' | 'marketing' | 'infrastructure';
  format: string;
  assignee: string;
  description: string;
  steps: string[];
}

export interface QualityGate {
  id: string; // UUID
  phase: string;
  criteria: string[];
  gatekeepers: string[];
  remediationPath: string;
}

export interface AIHandoff {
  id: string; // UUID
  taskName: string;
  targetAI: string;
  contextRequired: string[];
  promptTemplate: string;
  expectedOutputFormat: string;
  instructions: string;
}

export interface RiskItem {
  id: string; // UUID
  category: 'product' | 'technical' | 'timeline' | 'adoption';
  description: string;
  likelihood: 'Low' | 'Medium' | 'High';
  impact: 'Low' | 'Medium' | 'High';
  mitigation: string;
}

export interface AIConversationMessage {
  id: string; // UUID
  projectId: string; // UUID
  role: 'user' | 'assistant';
  message: string;
  createdAt: string;
}

export interface UserProfile {
  id: string; // UUID
  email: string;
  displayName: string;
  avatarUrl?: string;
  createdAt: string;
}

export interface ActivityLog {
  id: string; // UUID
  userId: string; // UUID
  action: string;
  details?: Record<string, any>;
  createdAt: string;
}

export interface Project {
  id: string; // UUID
  userId?: string; // UUID mapping to auth.uid()
  name: string;
  description: string;
  targetAudience: string;
  status: 'draft' | 'active' | 'archived';
  aiMetadata?: {
    model: string;
    provider: string;
    generationTime: string;
    durationMs: number;
  };
  createdAt: string;
  updatedAt: string;
  
  // OS components generated by AI
  strategy?: ProductStrategy;
  team?: TeamStructure;
  workflow?: WorkflowPhase[];
  deliverables?: Deliverable[];
  qualityGates?: QualityGate[];
  aiHandoffs?: AIHandoff[];
  risks?: RiskItem[];
  conversations?: AIConversationMessage[];
}
